# Сообщение в боссбаре
bossbar-title: "У тебя в инвентаре есть шалкер! Выйдешь - шалкер выпадет"

# Сообщение в консоли при выходе игрока с шалкерами
quit-message: "Игрок %player% вышел с шалкерами в инвентаре!"

# Цвет боссбара (RED, BLUE, GREEN, YELLOW, PURPLE, WHITE, PINK)
bossbar-color: "RED"